name: BabyGronk
version: '${version}'
main: io.github.avacadowizard120.babygronk.BabyGronk
api-version: '1.20'
load: POSTWORLD
authors: [Eden Urias]
description: Makes every baby zombie... Baby Gronk.
website: https://youtube.com/@ConfusingFool93
depend: [PlaceholderAPI]
